import { Inter } from 'next/font/google';
import ParentLayout from '@/components/ParentLayout';
import './globals.css';
import 'antd/dist/reset.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'G19 Tour & Travel',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ParentLayout>{children}</ParentLayout>
      </body>
    </html>
  );
}
